#!/usr/bin/env python3
"""
Build script to generate README.md with links to each space invaders game
and their commit history.
"""
import subprocess
import os
import re
from pathlib import Path


def linkify_urls(text):
    """Convert URLs in text to markdown links."""
    url_pattern = r'(https?://[^\s<>\[\]()]+)'
    return re.sub(url_pattern, r'<\1>', text)


def get_directories_by_creation():
    """Get all directories sorted by first commit date (most recent first)."""
    dirs = []
    for item in sorted(Path(".").iterdir()):
        if item.is_dir() and not item.name.startswith("."):
            # Get the first commit date for this directory
            result = subprocess.run(
                [
                    "git", "log",
                    "--format=%at",
                    "--diff-filter=A",
                    "--",
                    f"{item.name}/index.html"
                ],
                capture_output=True,
                text=True
            )
            timestamps = result.stdout.strip().split("\n")
            # First commit is the oldest (last in the list from git log)
            first_commit_ts = int(timestamps[-1]) if timestamps and timestamps[-1] else 0
            dirs.append((item.name, first_commit_ts))

    # Sort by timestamp descending (most recent first)
    dirs.sort(key=lambda x: x[1], reverse=True)
    return [d[0] for d in dirs]


def get_commit_history(directory):
    """Get commit history for a directory's index.html file."""
    result = subprocess.run(
        [
            "git", "log",
            "--format=%H|%ad|%s|%b",
            "--date=short",
            "--",
            f"{directory}/index.html"
        ],
        capture_output=True,
        text=True
    )

    commits = []
    if result.stdout.strip():
        # Split by newline but handle multi-line bodies
        lines = result.stdout.strip().split("\n")
        for line in lines:
            if "|" in line:
                parts = line.split("|", 3)
                if len(parts) >= 3:
                    commit_hash = parts[0]
                    date = parts[1]
                    subject = parts[2]
                    body = parts[3] if len(parts) > 3 else ""
                    commits.append({
                        "hash": commit_hash,
                        "date": date,
                        "subject": subject,
                        "body": body.strip()
                    })
    return commits


def build_readme():
    """Build the README.md file."""
    base_url = "https://space-invaders.simonwillison.net"
    repo_url = "https://github.com/simonw/space-invaders-by-llms"

    lines = [
        "# Space Invaders by LLMs",
        "",
        "A collection of Space Invaders games generated by various LLMs.",
        ""
    ]

    directories = get_directories_by_creation()

    for directory in directories:
        game_url = f"{base_url}/{directory}/"
        lines.append(f"## {directory}")
        lines.append("")
        lines.append(f"**Play:** <{game_url}>")
        lines.append("")

        commits = get_commit_history(directory)

        if commits:
            for commit in commits:
                commit_url = f"{repo_url}/commit/{commit['hash']}"
                subject = linkify_urls(commit['subject'])
                lines.append(f"- [{commit['date']}]({commit_url}): {subject}")
                if commit["body"]:
                    # Indent the body as a quote
                    for body_line in commit["body"].split("\n"):
                        if body_line.strip():
                            lines.append(f"  > {linkify_urls(body_line)}")
                lines.append("")

        lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    os.chdir(Path(__file__).parent)
    readme_content = build_readme()
    Path("README.md").write_text(readme_content)
    print("README.md generated successfully!")
    print()
    print(readme_content)
